/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */

plugins {
    kotlin("jvm") version "1.9.23"
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

group = "com.example"
version = "1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.amazonaws:aws-lambda-java-core:1.2.3")
    implementation("com.amazonaws:aws-lambda-java-events:3.11.4")
    implementation(platform("software.amazon.awssdk:bom:2.25.11"))
    implementation("software.amazon.awssdk:apigatewaymanagementapi")
    implementation("software.amazon.awssdk:url-connection-client")
    implementation("software.amazon.awssdk:dynamodb")
    implementation("software.amazon.awssdk:sagemakerruntime")
    implementation("software.amazon.awssdk:apigatewaymanagementapi:2.21.0")
    implementation("software.amazon.awssdk:url-connection-client:2.21.0")
    implementation("software.amazon.awssdk:cognitoidentityprovider:2.21.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.14.2")
    implementation(kotlin("stdlib"))

    // Test dependencies
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.9.23")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.0")
    testImplementation("io.mockk:mockk:1.13.10")
    testImplementation("uk.org.webcompere:system-stubs-jupiter:2.1.0")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.shadowJar {
    archiveBaseName.set("kotlin_app")
    archiveClassifier.set("all")
    archiveVersion.set("1.0")
    mergeServiceFiles()
}

tasks.test {
    useJUnitPlatform()
}
